"""Bounded, local-only office-document builders for Smara Desktop.

This module deliberately contains no networking and no path resolution.  The
desktop executor resolves every path against the paired user's approved roots,
holds the workspace lock, and handles previews/undo.  The functions here only
turn a small, reviewable JSON payload into document bytes.

The supported formats are intentionally useful rather than trying to emulate
Microsoft Office: DOCX reports, XLSX workbooks, PPTX briefings, and PDF
reports.  Macros, embedded scripts, external links, and arbitrary templates
are never accepted.
"""
from __future__ import annotations

from dataclasses import dataclass
from io import BytesIO
import re
from typing import Any, Callable


MAX_DOCUMENT_SECTIONS = 40
MAX_DOCUMENT_PARAGRAPHS = 300
MAX_DOCUMENT_BULLETS = 500
# This stays below the executor's 64 KB JSON payload envelope once section
# metadata is included, so a seemingly valid document is never rejected by a
# later transport guard.
MAX_DOCUMENT_TEXT_CHARS = 48_000
MAX_SHEETS = 12
MAX_ROWS_PER_SHEET = 1_000
MAX_CELLS_PER_WORKBOOK = 10_000
MAX_CELL_UPDATES = 1_000
MAX_SLIDES = 40
MAX_PDF_PAGES = 100

DOCUMENT_OPERATIONS = frozenset({
    "create_docx", "edit_docx",
    "create_xlsx", "edit_xlsx",
    "create_pptx", "edit_pptx",
    "create_pdf", "merge_pdf", "extract_pdf_pages",
})

_CELL = re.compile(r"^[A-Z]{1,3}[1-9][0-9]{0,6}$")
_SHEET_NAME = re.compile(r"^[^\\/*?:\[\]]{1,31}$")
_SAFE_FORMULA = re.compile(
    r"^=(?:SUM|AVERAGE|MIN|MAX|COUNT)\([A-Z]{1,3}[1-9][0-9]{0,6}(?::[A-Z]{1,3}[1-9][0-9]{0,6})?\)$",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class DocumentBuild:
    """The generated bytes and a secret-free preview for the approval UI."""

    data: bytes
    summary: dict[str, Any]


def is_document_operation(operation: object) -> bool:
    return isinstance(operation, str) and operation in DOCUMENT_OPERATIONS


def build_document(
    operation: str,
    payload: dict[str, Any],
    before: bytes,
    *,
    read_source: Callable[[object, str], bytes] | None = None,
) -> DocumentBuild:
    """Create or edit one bounded local office document.

    ``read_source`` is supplied by the executor for PDF merge/extract inputs;
    it keeps source paths under the executor's normal approved-root checks.
    """
    if operation == "create_docx":
        _require_extension(payload, ".docx")
        return _create_docx(payload)
    if operation == "edit_docx":
        _require_extension(payload, ".docx")
        return _edit_docx(payload, before)
    if operation == "create_xlsx":
        _require_extension(payload, ".xlsx")
        return _create_xlsx(payload)
    if operation == "edit_xlsx":
        _require_extension(payload, ".xlsx")
        return _edit_xlsx(payload, before)
    if operation == "create_pptx":
        _require_extension(payload, ".pptx")
        return _create_pptx(payload)
    if operation == "edit_pptx":
        _require_extension(payload, ".pptx")
        return _edit_pptx(payload, before)
    if operation == "create_pdf":
        _require_extension(payload, ".pdf")
        return _create_pdf(payload)
    if operation in {"merge_pdf", "extract_pdf_pages"}:
        _require_extension(payload, ".pdf")
        if read_source is None:
            raise RuntimeError("PDF source loading is unavailable.")
        return _transform_pdf(operation, payload, read_source)
    raise RuntimeError("Unsupported local document operation.")


def _require_extension(payload: dict[str, Any], extension: str) -> None:
    path = payload.get("path")
    if not isinstance(path, str) or not path.lower().endswith(extension):
        raise RuntimeError(f"This operation requires a {extension} destination path.")


def _text(value: object, field: str, *, required: bool = False, max_chars: int = MAX_DOCUMENT_TEXT_CHARS) -> str:
    if value is None and not required:
        return ""
    if not isinstance(value, str):
        raise RuntimeError(f"{field} must be text.")
    result = value.strip()
    if required and not result:
        raise RuntimeError(f"{field} is required.")
    if len(result) > max_chars:
        raise RuntimeError(f"{field} exceeds the local document text limit.")
    return result


def _title(payload: dict[str, Any], *, default: str) -> str:
    return _text(payload.get("title", default), "title", required=True, max_chars=240)


def _sections(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw = payload.get("sections", [])
    if raw is None:
        return []
    if not isinstance(raw, list) or len(raw) > MAX_DOCUMENT_SECTIONS:
        raise RuntimeError(f"sections must contain at most {MAX_DOCUMENT_SECTIONS} items.")
    result: list[dict[str, Any]] = []
    paragraph_count = 0
    bullet_count = 0
    chars = 0
    for index, item in enumerate(raw, 1):
        if not isinstance(item, dict) or set(item) - {"heading", "body", "paragraphs", "bullets"}:
            raise RuntimeError("Each section may contain only heading, body, paragraphs, and bullets.")
        heading = _text(item.get("heading"), f"sections[{index}].heading", max_chars=240)
        body = _text(item.get("body"), f"sections[{index}].body")
        paragraphs_raw = item.get("paragraphs", [])
        bullets_raw = item.get("bullets", [])
        if not isinstance(paragraphs_raw, list) or not isinstance(bullets_raw, list):
            raise RuntimeError("Section paragraphs and bullets must be lists of text.")
        paragraphs = [_text(value, "section paragraph", required=True) for value in paragraphs_raw]
        bullets = [_text(value, "section bullet", required=True, max_chars=2_000) for value in bullets_raw]
        paragraph_count += len(paragraphs) + (1 if body else 0)
        bullet_count += len(bullets)
        chars += len(heading) + len(body) + sum(map(len, paragraphs)) + sum(map(len, bullets))
        if paragraph_count > MAX_DOCUMENT_PARAGRAPHS or bullet_count > MAX_DOCUMENT_BULLETS or chars > MAX_DOCUMENT_TEXT_CHARS:
            raise RuntimeError("Document content exceeds its bounded local limit.")
        result.append({"heading": heading, "body": body, "paragraphs": paragraphs, "bullets": bullets})
    return result


def _create_docx(payload: dict[str, Any]) -> DocumentBuild:
    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover - packaging dependency
        raise RuntimeError("Word document support is not installed in Smara Desktop.") from exc
    title = _title(payload, default="Smara report")
    sections = _sections(payload)
    document = Document()
    document.add_heading(title, 0)
    for section in sections:
        if section["heading"]:
            document.add_heading(section["heading"], level=1)
        if section["body"]:
            document.add_paragraph(section["body"])
        for paragraph in section["paragraphs"]:
            document.add_paragraph(paragraph)
        for bullet in section["bullets"]:
            document.add_paragraph(bullet, style="List Bullet")
    output = BytesIO()
    document.save(output)
    return DocumentBuild(output.getvalue(), {"format": "docx", "title": title, "sections": len(sections), "mode": "created"})


def _edit_docx(payload: dict[str, Any], before: bytes) -> DocumentBuild:
    if not before:
        raise RuntimeError("edit_docx requires an existing Word document.")
    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("Word document support is not installed in Smara Desktop.") from exc
    try:
        document = Document(BytesIO(before))
    except Exception as exc:
        raise RuntimeError("The existing Word document could not be opened.") from exc
    operation = payload.get("edit")
    if operation == "append_sections":
        sections = _sections(payload)
        if not sections:
            raise RuntimeError("append_sections needs at least one section.")
        for section in sections:
            if section["heading"]:
                document.add_heading(section["heading"], level=1)
            if section["body"]:
                document.add_paragraph(section["body"])
            for paragraph in section["paragraphs"]:
                document.add_paragraph(paragraph)
            for bullet in section["bullets"]:
                document.add_paragraph(bullet, style="List Bullet")
        summary = {"format": "docx", "mode": "append_sections", "sections_added": len(sections)}
    elif operation == "replace_text":
        find = _text(payload.get("find"), "find", required=True, max_chars=8_000)
        replace = _text(payload.get("replace"), "replace", max_chars=8_000)
        matches = 0
        for paragraph in document.paragraphs:
            if find in paragraph.text:
                paragraph.text = paragraph.text.replace(find, replace)
                matches += 1
        if matches != 1:
            raise RuntimeError(f"Word replacement is ambiguous: expected 1 matching paragraph, found {matches}.")
        summary = {"format": "docx", "mode": "replace_text", "replacements": matches}
    else:
        raise RuntimeError("edit_docx supports edit='append_sections' or edit='replace_text'.")
    output = BytesIO()
    document.save(output)
    return DocumentBuild(output.getvalue(), summary)


def _sheet_name(value: object, field: str = "sheet name") -> str:
    name = _text(value, field, required=True, max_chars=31)
    if not _SHEET_NAME.fullmatch(name):
        raise RuntimeError("Excel sheet names may not contain \\ / * ? : [ or ].")
    return name


def _cell_value(value: object) -> str | int | float | bool | None:
    if value is None or isinstance(value, (str, int, float, bool)):
        if isinstance(value, str) and len(value) > 32_000:
            raise RuntimeError("A spreadsheet cell exceeds the text limit.")
        if isinstance(value, str) and value.startswith("="):
            raise RuntimeError("Spreadsheet formulas require the explicit formula field.")
        return value
    raise RuntimeError("Spreadsheet cells must contain text, numbers, booleans, or empty values.")


def _formula(value: object) -> str:
    formula = _text(value, "formula", required=True, max_chars=256)
    if not _SAFE_FORMULA.fullmatch(formula):
        raise RuntimeError("Only SUM, AVERAGE, MIN, MAX, and COUNT formulas over one local cell range are allowed.")
    return formula.upper()


def _create_xlsx(payload: dict[str, Any]) -> DocumentBuild:
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("Spreadsheet support is not installed in Smara Desktop.") from exc
    raw_sheets = payload.get("sheets")
    if not isinstance(raw_sheets, list) or not raw_sheets or len(raw_sheets) > MAX_SHEETS:
        raise RuntimeError(f"create_xlsx needs 1-{MAX_SHEETS} sheets.")
    workbook = Workbook()
    workbook.remove(workbook.active)
    total_cells = 0
    names: set[str] = set()
    for index, raw_sheet in enumerate(raw_sheets, 1):
        if not isinstance(raw_sheet, dict) or set(raw_sheet) - {"name", "rows", "freeze_header"}:
            raise RuntimeError("Each sheet may contain only name, rows, and freeze_header.")
        name = _sheet_name(raw_sheet.get("name"), f"sheets[{index}].name")
        if name.casefold() in names:
            raise RuntimeError("Spreadsheet sheet names must be unique.")
        names.add(name.casefold())
        rows = raw_sheet.get("rows")
        if not isinstance(rows, list) or len(rows) > MAX_ROWS_PER_SHEET:
            raise RuntimeError(f"Each spreadsheet sheet may contain at most {MAX_ROWS_PER_SHEET} rows.")
        sheet = workbook.create_sheet(name)
        for row_no, row in enumerate(rows, 1):
            if not isinstance(row, list) or len(row) > 200:
                raise RuntimeError("Each spreadsheet row must be a list with at most 200 cells.")
            total_cells += len(row)
            if total_cells > MAX_CELLS_PER_WORKBOOK:
                raise RuntimeError("Spreadsheet exceeds the 10,000-cell local limit.")
            for column_no, value in enumerate(row, 1):
                cell = sheet.cell(row_no, column_no, _cell_value(value))
                if row_no == 1:
                    cell.font = Font(bold=True)
        if raw_sheet.get("freeze_header") is True and rows:
            sheet.freeze_panes = "A2"
    output = BytesIO()
    workbook.save(output)
    return DocumentBuild(output.getvalue(), {"format": "xlsx", "mode": "created", "sheets": len(raw_sheets), "cells": total_cells})


def _edit_xlsx(payload: dict[str, Any], before: bytes) -> DocumentBuild:
    if not before:
        raise RuntimeError("edit_xlsx requires an existing spreadsheet.")
    try:
        import openpyxl
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("Spreadsheet support is not installed in Smara Desktop.") from exc
    try:
        workbook = openpyxl.load_workbook(BytesIO(before), keep_vba=False, data_only=False)
    except Exception as exc:
        raise RuntimeError("The existing spreadsheet could not be opened.") from exc
    updates = payload.get("cells")
    if not isinstance(updates, list) or not updates or len(updates) > MAX_CELL_UPDATES:
        raise RuntimeError(f"edit_xlsx needs 1-{MAX_CELL_UPDATES} cell updates.")
    changed = 0
    for index, update in enumerate(updates, 1):
        if not isinstance(update, dict) or set(update) - {"sheet", "cell", "value", "formula"}:
            raise RuntimeError("Each cell update may contain only sheet, cell, value, and formula.")
        sheet_name = _sheet_name(update.get("sheet"), f"cells[{index}].sheet")
        if sheet_name not in workbook.sheetnames:
            raise RuntimeError(f"Spreadsheet sheet '{sheet_name}' does not exist.")
        cell = update.get("cell")
        if not isinstance(cell, str) or not _CELL.fullmatch(cell.upper()):
            raise RuntimeError("Spreadsheet cell references must look like A1.")
        has_value, has_formula = "value" in update, "formula" in update
        if has_value == has_formula:
            raise RuntimeError("Each cell update must contain exactly one of value or formula.")
        workbook[sheet_name][cell.upper()] = _cell_value(update["value"]) if has_value else _formula(update["formula"])
        changed += 1
    output = BytesIO()
    workbook.save(output)
    return DocumentBuild(output.getvalue(), {"format": "xlsx", "mode": "edited", "cells_updated": changed})


def _slides(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw = payload.get("slides")
    if not isinstance(raw, list) or not raw or len(raw) > MAX_SLIDES:
        raise RuntimeError(f"slides must contain 1-{MAX_SLIDES} items.")
    result: list[dict[str, Any]] = []
    for index, item in enumerate(raw, 1):
        if not isinstance(item, dict) or set(item) - {"title", "body", "bullets"}:
            raise RuntimeError("Each slide may contain only title, body, and bullets.")
        title = _text(item.get("title"), f"slides[{index}].title", required=True, max_chars=240)
        body = _text(item.get("body"), f"slides[{index}].body", max_chars=6_000)
        bullets = item.get("bullets", [])
        if not isinstance(bullets, list) or len(bullets) > 40:
            raise RuntimeError("Each slide may contain at most 40 bullets.")
        result.append({"title": title, "body": body, "bullets": [_text(item, "slide bullet", required=True, max_chars=1_000) for item in bullets]})
    return result


def _add_slide(presentation: Any, slide_data: dict[str, Any]) -> None:
    slide = presentation.slides.add_slide(presentation.slide_layouts[1])
    slide.shapes.title.text = slide_data["title"]
    frame = slide.placeholders[1].text_frame
    frame.clear()
    first = True
    if slide_data["body"]:
        frame.paragraphs[0].text = slide_data["body"]
        first = False
    for bullet in slide_data["bullets"]:
        paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
        paragraph.text = bullet
        paragraph.level = 0
        first = False


def _create_pptx(payload: dict[str, Any]) -> DocumentBuild:
    try:
        from pptx import Presentation
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("Presentation support is not installed in Smara Desktop.") from exc
    title = _title(payload, default="Smara briefing")
    slides = _slides(payload)
    presentation = Presentation()
    title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
    title_slide.shapes.title.text = title
    subtitle = _text(payload.get("subtitle"), "subtitle", max_chars=240)
    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = subtitle
    for slide in slides:
        _add_slide(presentation, slide)
    output = BytesIO()
    presentation.save(output)
    return DocumentBuild(output.getvalue(), {"format": "pptx", "mode": "created", "title": title, "slides": len(slides) + 1})


def _edit_pptx(payload: dict[str, Any], before: bytes) -> DocumentBuild:
    if not before:
        raise RuntimeError("edit_pptx requires an existing presentation.")
    try:
        from pptx import Presentation
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("Presentation support is not installed in Smara Desktop.") from exc
    if payload.get("edit") != "append_slides":
        raise RuntimeError("edit_pptx supports edit='append_slides' only.")
    try:
        presentation = Presentation(BytesIO(before))
    except Exception as exc:
        raise RuntimeError("The existing presentation could not be opened.") from exc
    slides = _slides(payload)
    if len(presentation.slides) + len(slides) > MAX_SLIDES + 1:
        raise RuntimeError("Presentation exceeds the 41-slide local limit.")
    for slide in slides:
        _add_slide(presentation, slide)
    output = BytesIO()
    presentation.save(output)
    return DocumentBuild(output.getvalue(), {"format": "pptx", "mode": "append_slides", "slides_added": len(slides)})


def _create_pdf(payload: dict[str, Any]) -> DocumentBuild:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfbase.pdfmetrics import stringWidth
        from reportlab.pdfgen import canvas
    except ImportError as exc:  # pragma: no cover - packaging dependency
        raise RuntimeError("PDF report support is not installed in Smara Desktop.") from exc
    title = _title(payload, default="Smara report")
    sections = _sections(payload)
    # ReportLab's bundled base fonts are Latin-only. Refuse text those fonts
    # cannot render rather than silently producing black-square glyphs. DOCX,
    # XLSX and PPTX remain Unicode-native; a bundled Indic font is a separate
    # desktop asset rather than an unreviewed system-font dependency.
    pdf_text = [title]
    for section in sections:
        pdf_text.extend([section["heading"], section["body"], *section["paragraphs"], *section["bullets"]])
    if any(any(ord(char) > 255 for char in value) for value in pdf_text):
        raise RuntimeError("PDF reports currently need Latin-based text. Use DOCX, XLSX, or PPTX for Unicode text until Smara's packaged Indic PDF font is enabled.")
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4, pageCompression=1)
    width, height = A4
    x, y = 54, height - 58
    pages = 1

    def line(text: str, size: int = 10, *, bold: bool = False, indent: int = 0) -> None:
        nonlocal y, pages
        font = "Helvetica-Bold" if bold else "Helvetica"
        pdf.setFont(font, size)
        max_width = width - x - 54 - indent
        words = text.split() or [""]
        current = ""
        for word in words:
            candidate = word if not current else f"{current} {word}"
            if current and stringWidth(candidate, font, size) > max_width:
                if y < 58:
                    pdf.showPage(); pages += 1; y = height - 58; pdf.setFont(font, size)
                pdf.drawString(x + indent, y, current)
                y -= size + 5
                current = word
            else:
                current = candidate
        if y < 58:
            pdf.showPage(); pages += 1; y = height - 58; pdf.setFont(font, size)
        pdf.drawString(x + indent, y, current)
        y -= size + 7

    line(title, 18, bold=True)
    y -= 8
    for section in sections:
        if section["heading"]:
            line(section["heading"], 13, bold=True)
        if section["body"]:
            line(section["body"])
        for paragraph in section["paragraphs"]:
            line(paragraph)
        for bullet in section["bullets"]:
            line(f"- {bullet}", indent=12)
        y -= 5
    pdf.save()
    return DocumentBuild(buffer.getvalue(), {"format": "pdf", "mode": "created", "title": title, "sections": len(sections), "pages": pages})


def _transform_pdf(operation: str, payload: dict[str, Any], read_source: Callable[[object, str], bytes]) -> DocumentBuild:
    try:
        from pypdf import PdfReader, PdfWriter
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("PDF support is not installed in Smara Desktop.") from exc
    writer = PdfWriter()
    if operation == "merge_pdf":
        sources = payload.get("source_paths")
        if not isinstance(sources, list) or not 2 <= len(sources) <= 10:
            raise RuntimeError("merge_pdf needs 2-10 approved source PDF paths.")
        pages = 0
        for index, source in enumerate(sources, 1):
            raw = read_source(source, f"source_paths[{index}]")
            try:
                reader = PdfReader(BytesIO(raw))
            except Exception as exc:
                raise RuntimeError("One source PDF could not be opened.") from exc
            if reader.is_encrypted:
                raise RuntimeError("Encrypted PDFs cannot be merged locally.")
            pages += len(reader.pages)
            if pages > MAX_PDF_PAGES:
                raise RuntimeError(f"Merged PDF exceeds the {MAX_PDF_PAGES}-page limit.")
            for page in reader.pages:
                writer.add_page(page)
        summary = {"format": "pdf", "mode": "merged", "sources": len(sources), "pages": pages}
    else:
        raw = read_source(payload.get("source_path"), "source_path")
        try:
            reader = PdfReader(BytesIO(raw))
        except Exception as exc:
            raise RuntimeError("The source PDF could not be opened.") from exc
        if reader.is_encrypted:
            raise RuntimeError("Encrypted PDFs cannot be extracted locally.")
        raw_pages = payload.get("pages")
        if not isinstance(raw_pages, list) or not raw_pages or len(raw_pages) > MAX_PDF_PAGES:
            raise RuntimeError(f"extract_pdf_pages needs 1-{MAX_PDF_PAGES} page numbers.")
        pages: list[int] = []
        for value in raw_pages:
            if not isinstance(value, int) or isinstance(value, bool) or value < 1 or value > len(reader.pages):
                raise RuntimeError("Requested PDF page is outside the source document.")
            if value in pages:
                raise RuntimeError("Requested PDF pages must not repeat.")
            pages.append(value)
            writer.add_page(reader.pages[value - 1])
        summary = {"format": "pdf", "mode": "extracted_pages", "pages": pages}
    output = BytesIO()
    writer.write(output)
    return DocumentBuild(output.getvalue(), summary)
